#!/usr/bin/env bash
# Script: transfer_file.sh
# Description: This script transfers a file from a client to a server using scp.

# Check if all parameters are provided
if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assigning parameters to variables
FILE_PATH="$1"
SERVER_IP="$2"
USERNAME="$3"
SSH_KEY="$4"

# Transfer file using scp
scp -o StrictHostKeyChecking=no -i "$SSH_KEY" "$FILE_PATH" "$USERNAME@$SERVER_IP:~/"

# Check the exit status of scp command
if [ "$?" -eq 0 ]; then
    echo "File transfer successful"
else
    echo "File transfer failed"
fi

