#!/usr/bin/env bash

# Set the filename for the private key
private_key="school"

# Generate RSA key pair with 4096 bits and protect it with the passphrase "betty"
ssh-keygen -t rsa -b 4096 -f ~/.ssh/"$private_key" -N "betty"

echo "RSA key pair with the filename \"$private_key\" has been created with 4096 bits and protected by the passphrase \"betty\"."

